services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file: .env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
  api:
    container_name: api
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - mongodb
      - rabbitmq

  notification-consumer:
    container_name: notification-consumer
    build:
      context: .
      dockerfile: notification-consumer/Dockerfile
    env_file: .env
    depends_on:
      - rabbitmq

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:3000"
    env_file: frontend/.env
    depends_on:
      - api

volumes:
  rabbitmq_data:
  rabbitmq_logs:
