spring:
  application:
    name: project

server:
  servlet:
    context-path: /api/v1

---
spring:
  mongodb:
    uri: ${MONGO_URI}
    database: ${MONGO_DB}

api:
  security:
    token:
      secret: ${JWT_SECRET}
      expired: ${JWT_EXPIRED}

logging:
  level:
    org:
      springframework:
        security: DEBUG
