spring:
  application:
    name: project

server:
  servlet:
    context-path: /api/v1

---
spring:
  mongodb:
    uri: ${MONGO_URI}
    database: ${MONGO_DB}
    username: ${MONGO_USER}
    password: ${MONGO_PASSWORD}

api:
  security:
    token:
      secret: ${JWT_SECRET}
      expired: ${JWT_EXPIRED}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10