spring:
  application:
    name: project

server:
  servlet:
    context-path: /api/v1

---
spring:
  data:
    mongodb:
      uri: ${MONGO_URI}/${MONGO_DB}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

api:
  security:
    token:
      secret: ${JWT_SECRET}
      expired: ${JWT_EXPIRED}

---
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10